### ISSUE TITLE
enable react components in message

### ISSUE THREAD

**Issue by amit034** [LouisBarranqueiro/reapop#2]
allow notification message to contain react components in message in case of AllowHTML = true 

```
const refreshList = function(){...};
            const msg =(<div><span>Updated Successfully<span><a href="#" onclick={refreshList}></a></div>);
            notifier.message= msg;
            notifier.allowHTML=true;
            notifier.status = 'success';

            notifier.dismissible = true;
            notifier.dismissAfter = 15000;
            notifier.buttons=[{
                name: 'OK',
                primary: true,
                onClick: () => {
                }
            }];
            dispatch(updateNotification(notifier));
```

creates message with [object Object]

**Comment by LouisBarranqueiro** [comment]
Hey @amit034, yeah message must be a string and not JSX. Why would you like to render a component inside the notification?

**Comment by amit034** [comment]
i would like to build something that more interactive and could have more then 2 buttons.
in my case i have a notification with "refresh list" link that dispatch fetch items and another button for message details.

**Comment by LouisBarranqueiro** [comment]
what do you means by more interactive?
And more buttons? in your case : 
- button 1 : refresh list
- button 2 : message details
- button 3 : ?

**Comment by amit034** [comment]
i need the refresh list as a link in the bottom  left corner. currently i have fix it with css

**Comment by LouisBarranqueiro** [comment]
yeah, but why a link instead of a button?

**Comment by leefsmp** [comment]
I like the component and it's been pretty handy so far, but would be super nice if you were a bit more open to enhancements... Being able to inject a custom React component inside the popup would be very powerful and would suppress the need to implement features at the lib level. The needs of developers can go beyond the classic use cases you may have in mind, why not leveraging React flexibility...? I would like to be able to inject in the popup a custom progress bar or some more fancy components from my app, I guess I will have to find another lib or write my own  :(

**Comment by LouisBarranqueiro** [comment]
👋 @leefsmp 

> I like the component and it's been pretty handy so far, but would be super nice if you were a bit more open to enhancements... 

What makes you say that? Here, I'm trying to understand the needs of this user, that's why I asked questions because I felt he didn't need this feature. He didn’t respond so I just decided to close it. I want to make this library simple to use, so every feature/improvement implemented need to be a must and not a nice to have. But I never said "no" to this feature.

> Being able to inject a custom React component inside the popup would be very powerful and would suppress the need to implement features at the lib level. The needs of developers can go beyond the classic use cases you may have in mind, why not leveraging React flexibility...? I would like to be able to inject in the popup a custom progress bar or some more fancy components from my app, I guess I will have to find another lib or write my own :(

I think you didn't understand what open source is and what's not. Open source is not a way to ask others to implement what you want. It's a way to build something together and you are included in this "together". It also enables you to adapt and extend base projects by yourself; and why not give something back at the end. That’s what open source is. 

With that been said, if you want this feature, you could open an issue explaining what you want, why you want it (use cases) so we can maybe build this feature?

**Comment by NeXTs** [comment]
It's still not possible to use react components in messages?
In my case, I need to show the custom user's avatar (which is react component in my app) in the message content.
