### ISSUE TITLE
Hydration Mismatch in Next.js v13

### ISSUE THREAD

**Issue by OmegaHawkeye** [LouisBarranqueiro/reapop#512]
### Description

After refreshing the browser once, I get a hydration mismatch error message and looking at the dev console I can see its bc of reapop( specifically the prop "className" )

### Expected behavior

Not a hydration mismatch. 

![image](https://user-images.githubusercontent.com/51196565/204928455-ee31c292-c602-4dd1-b4c4-4a70db103128.png)

### Steps to reproduce the bug
 
 Add Reapop to a new next js v13 project and after getting a notification and refreshing the error occurs 

### Environment
 - **OS name and version** :  Windows 10 Pro
 - **Browser name and version**: Brave version 1.45.133 Chromium: 107.0.5304.141 (Official Build) (64-bit)
 - **Reapop version**: 4.2.0

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @OmegaHawkeye, I would need a way to reproduce this problem to understand it and see if it comes from your app or the library. Could you please set a [code sandbox](https://codesandbox.io/) environment with Next and Reapop?

**Comment by bannik** [comment]
A solution to this is to check if your app "is mounted" aka check if `window` is available to the react wrapper. You can do so by creating a file called useIsMounted (in order to be able to use it in other places if needed as well).
The file should look something like this:

`import React from "react";

export function useIsMounted() {
  const [mounted, setMounted] = React.useState(false);

  React.useEffect(() => setMounted(true), []);

  return mounted;
}
` 

Now within the file you call the NotificationsSystem you need to do the following:
`
  const isMounted = useIsMounted();
  return (
    <div>
      {isMounted && (
        <NotificationsSystem
          // 2. Pass the notifications you want Reapop to display.
          notifications={notifications}
          // 3. Pass the function used to dismiss a notification.
          dismissNotification={(id) => dismissNotification(id)}
          // 4. Pass a builtIn theme or a custom theme.
          theme={atalhoTheme}
        />
      )}
      [...]
    </div>
  );
`

Of course, you would need to import useIsMounted from the file you are exporting it at. I hope that helped.

**Comment by LouisBarranqueiro** [comment]
> 👋 @OmegaHawkeye, I would need a way to reproduce this problem to understand it and see if it comes from your app or the library. Could you please set a [code sandbox](https://codesandbox.io/) environment with Next and Reapop?

I'm closing this issue for now. If you still encounter this problem, please feel free to reopen this issue with more information so I can investigate this problem.
