### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by LouisBarranqueiro** [LouisBarranqueiro/reapop#61]

**Comment by anonrig** [comment]
Any timeline on this?

**Comment by LouisBarranqueiro** [comment]
👋 @anonrig, Reapop is already compatible with React 16.  But I need to run the whole test suite on React 16 to say "it officially supports React 16" and this is where the big work starts.

**Comment by anonrig** [comment]
Thank you for your fast reply @LouisBarranqueiro . I'm eager to use reapop but official support for React 16 is important. Since, I'm having these kinds of errors, even though I followed the guideline 100%.

<img width="519" alt="screen shot 2017-11-24 at 2 26 50 pm" src="https://user-images.githubusercontent.com/1935246/33208688-963ce6e0-d123-11e7-959a-e84961810d7b.png">

**Comment by LouisBarranqueiro** [comment]
@anonrig this error is not related to React 16. You didn't initialized the notification reducer correctly. Read this issue to solve your problem: https://github.com/LouisBarranqueiro/reapop/issues/46

**Comment by emekalites** [comment]
can i fork the master branch and use it in react@16.0.0 without issues? I would really love to use this plugin

**Comment by LouisBarranqueiro** [comment]
@emekalites you don't have to fork it unless you want to change some stuff but yeah, you can use it.

**Comment by emekalites** [comment]
okay thanks

**Comment by RaedsLab** [comment]
+1 To updating dependencies
